"""定义 QQ 协议常量。"""

QQ_OFFICIAL_GATEWAY_NAME = "qq_official_gateway"
SUPPORTED_CONFIG_VERSION = "1.1.0"

APP_ACCESS_TOKEN_URL = "https://bots.qq.com/app/getAppAccessToken"
ACCESS_TOKEN_REFRESH_MARGIN_SEC = 120

API_BASE_PRODUCTION = "https://api.sgroup.qq.com"
API_BASE_SANDBOX = "https://sandbox.api.sgroup.qq.com"

OP_DISPATCH = 0
OP_HEARTBEAT = 1
OP_IDENTIFY = 2
OP_RESUME = 6
OP_RECONNECT = 7
OP_INVALID_SESSION = 9
OP_HELLO = 10
OP_HEARTBEAT_ACK = 11

EVENT_READY = "READY"
EVENT_RESUMED = "RESUMED"
EVENT_GROUP_AT_MESSAGE_CREATE = "GROUP_AT_MESSAGE_CREATE"
EVENT_C2C_MESSAGE_CREATE = "C2C_MESSAGE_CREATE"
EVENT_GROUP_MESSAGE_CREATE = "GROUP_MESSAGE_CREATE"
EVENT_AT_MESSAGE_CREATE = "AT_MESSAGE_CREATE"
EVENT_MESSAGE_CREATE = "MESSAGE_CREATE"
EVENT_DIRECT_MESSAGE_CREATE = "DIRECT_MESSAGE_CREATE"

MESSAGE_CREATE_EVENTS = {
    EVENT_GROUP_AT_MESSAGE_CREATE,
    EVENT_GROUP_MESSAGE_CREATE,
    EVENT_C2C_MESSAGE_CREATE,
    EVENT_AT_MESSAGE_CREATE,
    EVENT_MESSAGE_CREATE,
    EVENT_DIRECT_MESSAGE_CREATE,
}

INTENT_GROUP_AND_C2C_EVENT = 1 << 25
INTENT_PUBLIC_GUILD_MESSAGES = 1 << 30
INTENT_DIRECT_MESSAGE = 1 << 12
DEFAULT_INTENTS = INTENT_DIRECT_MESSAGE | INTENT_GROUP_AND_C2C_EVENT | INTENT_PUBLIC_GUILD_MESSAGES
DEFAULT_ACTION_TIMEOUT_SEC = 10.0
DEFAULT_RECONNECT_DELAY_SEC = 5.0
DEFAULT_SHARD_COUNT = 1
DEFAULT_SHARD_ID = 0

# 预留一分钟，避免在网络往返期间越过平台有效期。
GROUP_PASSIVE_REPLY_TTL_SEC = 4 * 60
PRIVATE_PASSIVE_REPLY_TTL_SEC = 59 * 60
MAX_GROUP_PASSIVE_REPLIES_PER_MESSAGE = 5
MAX_PRIVATE_PASSIVE_REPLIES_PER_MESSAGE = 4

HEARTBEAT_FAIL_LIMIT = 2
MAX_INBOUND_MEDIA_BYTES = 20 * 1024 * 1024
INBOUND_MESSAGE_DEDUP_TTL_SEC = 10 * 60
TRUSTED_QQ_MEDIA_HOSTS = frozenset({"multimedia.nt.qq.com.cn"})
